apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-test-
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: ghcr.io/yteraoka/diag-tools:0.5.0
        command:
          - sh
          - -c
        args:
          - "echo begin; for i in $(seq 30); do date; sleep 1; done; echo end"
      restartPolicy: Never
